Screen template
infinitered/ignite-ir-boilerplate-2016 pull request #9
Opened 2017-03-07 07:22 UTC by mwarger

updated to use screen-style instead of saga
fixed typo in tests

2017-03-07 10:14 UTC, skellock requested changes
Thanks.  Could you run the linter on this please?

2017-03-07 15:47 UTC, mwarger commented
Linting completed.

2017-03-09 05:43 UTC, mwarger commented
@skellock Please let me know if there's anything else I should do.  Thanks!

2017-03-09 12:38 UTC, skellock requested changes

2017-03-09 12:38 UTC, skellock commented on commands/screen.js
> +module.exports = async function(context) {
This needs a space between function and (context).  You can run `npm run standard` to find these issues.

2017-03-09 12:38 UTC, skellock commented on commands/screen.js
> +  }
This trailing space will be picked up by the linter.

2017-03-09 12:39 UTC, skellock commented
Looks like that file was missed by the linting.  If you could patch that up, we're good to go!

Thank you kindly.

2017-03-09 20:26 UTC, mwarger commented
Ok, it looks like it passed linting.  Thanks for your help!

2017-03-09 22:11 UTC, skellock approved these changes

2017-03-09 22:11 UTC, merged

2017-03-09 22:11 UTC, skellock commented
Thank you sir!